apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: {{VERSION}}
controlPlaneEndpoint: "{{MASTER_VIP}}:6443"
networking:
    podSubnet: "{{POD_CIDR}}"
    # serviceSubnet: "10.96.0.0/16"
imageRepository: registry.aliyuncs.com/google_containers
